# Generated by Django 4.2.5 on 2023-09-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='AppUsers',
        ),
    ]
